server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-1
    driver-class-name: org.postgresql.Driver
    username: kpo-idz4
    password: kpo-idz4
  jpa:
    hibernate:
      ddl-auto: none

